# Generated by Django 5.0.4 on 2024-05-05 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemtype',
            name='item',
        ),
        migrations.AddField(
            model_name='item',
            name='item_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='items.itemtype'),
        ),
    ]
