# Generated by Django 5.0.4 on 2024-05-05 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localizations', '0002_room_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localizations.address'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
