# Generated by Django 5.0.4 on 2024-04-19 18:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notification_type', models.CharField(choices=[('single_use', 'Jednorazowe'), ('cyclical', 'Cykliczne'), ('reminder', 'Przypomnienie')], default=('single_use', 'Jednorazowe'), max_length=50)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('frequency', models.IntegerField(blank=True, null=True)),
                ('time_before', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('recipients', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Powiadomienie',
                'verbose_name_plural': 'Powiadomienia',
                'ordering': ['-is_active', '-created_at', '-notification_type'],
            },
        ),
    ]
