# Generated by Django 5.0.4 on 2024-04-14 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
