# Generated by Django 5.0.4 on 2024-04-14 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_start_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-is_active', '-created_at', '-start_date', '-frequency'], 'verbose_name': 'Powiadomienie', 'verbose_name_plural': 'Powiadomienia'},
        ),
        migrations.AddField(
            model_name='notification',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
