# Generated by Django 5.0.4 on 2024-04-15 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_options_notification_is_active'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='recipients',
            field=models.ManyToManyField(to='users.customuser'),
        ),
    ]
