# Generated by Django 5.0.4 on 2024-04-16 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notification_recipients'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-is_active', '-created_at', '-notification_type'], 'verbose_name': 'Powiadomienie', 'verbose_name_plural': 'Powiadomienia'},
        ),
        migrations.AddField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('single_use', 'Jednorazowe'), ('cyclical', 'Cykliczne'), ('reminder', 'Przypomnienie')], default=('single_use', 'Jednorazowe'), max_length=50),
        ),
        migrations.AddField(
            model_name='notification',
            name='time_before',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='frequency',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
