# Generated by Django 5.0.4 on 2024-04-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_alter_notification_date_alter_notification_frequency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='time_before',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
